config/routes.rb
Heatmaps::Application.routes.draw do
  root 'static#index'
  resources :neighborhoods

end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  validates :RegionName, presence: true

  def address
    return self.RegionName+", "+self.City+", "+self.State
  end

  def geo
      coords = Geokit::Geocoders::MultiGeocoder.geocode(address)
      self.Latitude = coords.lat
      self.Longitude = coords.lng
      puts coords
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy]

  def index
    @neighborhoods = Neighborhood.all
    respond_to do |format|
      format.json { render json: @neighborhoods }
    end
  end

  
  def show
  end

  def new
    @neighborhood = Neighborhood.new
  end

  def edit
  end

  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully created.' }
        format.json { render action: 'show', status: :created, location: @neighborhood }
      else
        format.html { render action: 'new' }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @neighborhood.update(neighborhood_params)
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @neighborhood.destroy
    respond_to do |format|
      format.html { redirect_to neighborhoods_url }
      format.json { head :no_content }
    end
  end

  private

    def set_neighborhood
      @neighborhood = Neighborhood.find(params[:id])
    end

    def neighborhood_params
      params.require(:neighborhood).permit(:RegionName, :City, :State, :Metro, :CountyName, :AvgRentPrice, :Latitude, :Longitude, :ViolentCrimePer10kCapita)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heatmaps</title>
  <script src=
    "https://maps.googleapis.com/maps/api/js?key=AIzaSyBdacxIPLBmGeowW3ICo1quEftRP7DbA2k">
  </script>
  <script type=
     "text/javascript" src="https://www.google.com/jsapi">
  </script>

  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/neighborhoods/_form.html.erb
<%= form_for(@neighborhood) do |f| %>
  <% if @neighborhood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h2>

      <ul>
      <% @neighborhood.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :RegionName %><br>
    <%= f.text_field :RegionName %>
  </div>
  <div class="field">
    <%= f.label :City %><br>
    <%= f.text_field :City %>
  </div>
  <div class="field">
    <%= f.label :State %><br>
    <%= f.text_field :State %>
  </div>
  <div class="field">
    <%= f.label :Metro %><br>
    <%= f.text_field :Metro %>
  </div>
  <div class="field">
    <%= f.label :CountryName %><br>
    <%= f.text_field :CountryName %>
  </div>
  <div class="field">
    <%= f.label :AvgRentPrice %><br>
    <%= f.text_field :AvgRentPrice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/neighborhoods/edit.html.erb
<h1>Editing neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Show', @neighborhood %> |
<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/index.html.erb
<h1>Listing neighborhoods</h1>

<table>
  <thead>
    <tr>
      <th>Regionname</th>
      <th>City</th>
      <th>State</th>
      <th>Metro</th>
      <th>Countyname</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Avgrentprice</th>
      <th>ViolentCrimePer10kCapita</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @neighborhoods.each do |neighborhood| %>
      <tr>
        <td><%= neighborhood.RegionName %></td>
        <td><%= neighborhood.City %></td>
        <td><%= neighborhood.State %></td>
        <td><%= neighborhood.Metro %></td>
        <td><%= neighborhood.CountyName %></td>
        <td><%= neighborhood.Latitude %></td>
        <td><%= neighborhood.Longitude %></td>
        <td><%= neighborhood.AvgRentPrice %></td>
        <td><%= neighborhood.ViolentCrimePer10kCapita %></td>        
        <td><%= link_to 'Show', neighborhood %></td>
        <td><%= link_to 'Edit', edit_neighborhood_path(neighborhood) %></td>
        <td><%= link_to 'Destroy', neighborhood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Neighborhood', new_neighborhood_path %>

app/views/neighborhoods/new.html.erb
<h1>New neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Regionname:</strong>
  <%= @neighborhood.RegionName %>
</p>

<p>
  <strong>City:</strong>
  <%= @neighborhood.City %>
</p>

<p>
  <strong>State:</strong>
  <%= @neighborhood.State %>
</p>

<p>
  <strong>Metro:</strong>
  <%= @neighborhood.Metro %>
</p>

<p>
  <strong>Countryname:</strong>
  <%= @neighborhood.CountryName %>
</p>

<p>
  <strong>Avgrentprice:</strong>
  <%= @neighborhood.AvgRentPrice %>
</p>

<%= link_to 'Edit', edit_neighborhood_path(@neighborhood) %> |
<%= link_to 'Back', neighborhoods_path %>